### ISSUE TITLE
question: how to contribute to the wiki?

### ISSUE THREAD

**Issue by monperrus** [ModelInference/synoptic#415]
I'd like to improve the wiki based on my getting-started problems and surprises.

how to contribute to the wiki?

**Comment by bestchai** [comment]
First of all, thanks! That would be a big help.

I was thinking that pull requests would work for this (since the wiki is part of the git repo), but apparently github doesn't support this.

Two simple alternatives -- (1)  I give you push access and you modify the wiki directly. Or, (2) you clone the wiki and push your changes to a temporary repo where I can preview them and pull them into the project.

If you're just planning on creating a single getting-started page then (2) works fine. If you'll be editing all over the wiki, then (1) is justified.

**Comment by monperrus** [comment]
Two other options that support classical PRs:

1) put the wiki in the main source folder and rely on Github's builtin
viewer. This is what we do for https://github.com/INRIA/spoon/

2) put the wiki in a branch gh-pages and browse it on
http://ModelInference.github.io/synoptic/

**Comment by monperrus** [comment]
Or simplest solution:
untick "Restrict editing to users in teams with push access only." in the project settings

**Comment by bestchai** [comment]
Okay, done -- I unticked that setting.
